### ISSUE TITLE
Logs are getting written to cmd.exe

### ISSUE THREAD

**Issue by NavyaSindhu** [jwijffels/taskscheduleR#33] opened 2018-03-23 13:06 UTC
When I run my task instantly, logs are not getting written to log file in the same path which got created instead it is being written to cmd.exe. The moment anything fails cmd gets closed and also, loga are lost.

**Comment by jwijffels** [comment] 2018-03-23 18:41
Please provide a reproducible example of your issue

**Comment by NavyaSindhu** [comment] 2018-03-26 06:58
To replicate the issue, try running two different tasks from two different instances of RStudio.

**Comment by jwijffels** [comment] 2018-03-26 11:01
You need to provide a reproducible example of the exact steps you did (as in provide code) before I can able to help.

**Comment by NavyaSindhu** [comment] 2018-03-26 12:31
Following piece of code I ran from my first instance of RStudio:

script <- system.file("extdata", "Script1.R", package = "taskscheduleR")
taskscheduler_create(taskname = "BuildScript1", rscript = script)
taskcheduler_runnow("BuildScript1")
This wrote log to the path where script1 exists.

After creating one more project in other instance of RStudio, I ran

script <- system.file("extdata", "Script2.R", package = "taskscheduleR")
taskscheduler_create(taskname = "BuildScript2", rscript = script)
taskcheduler_runnow("BuildScript2")

But in this case, BuildScript2.log file did get created but all my print statements were printing to cmd.

**Comment by jwijffels** [comment] 2018-03-26 16:43
I can't reproduce this behaviour.

**Comment by jwijffels** [comment] 2018-10-25 21:11
Closing as no active feedback given in last month.

**Closed as completed by jwijffels** 2018-10-25 21:11 UTC
